2018-04-13 22:43:03,912 Scan.py[line:189] ERROR <expected an indented block (st2_eval.py, line 42)>
2018-04-13 22:43:09,758 Scan.py[line:76] ERROR <'NoneType' object has no attribute 'string'>
2018-04-13 22:43:10,012 crack_redis.py[line:35] ERROR <45.78.54.37 [Errno 61] Connection refused>
